import { Mark, mergeAttributes } from '@tiptap/core';

export interface AiHighlightOptions {
  HTMLAttributes: Record<string, any>;
}

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    aiHighlight: {
      setAiHighlight: (attributes?: { type: 'typo' | 'grammar' | 'expression', id: string }) => ReturnType;
      unsetAiHighlight: (id?: string) => ReturnType;
    };
  }
}

export const AiHighlight = Mark.create<AiHighlightOptions>({
  name: 'aiHighlight',

  addOptions() {
    return {
      HTMLAttributes: {},
    };
  },

  addAttributes() {
    return {
      id: {
        default: null,
      },
      type: {
        default: 'typo',
        renderHTML: (attributes) => {
          return {
            'data-type': attributes.type,
            class: `ai-highlight-${attributes.type}`,
          };
        },
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'span[data-type]',
        getAttrs: (element) => {
          if (typeof element === 'string') return false;
          return {
             type: element.getAttribute('data-type'),
             id: element.getAttribute('id'), // Assuming id might be stored or handled differently, but keeping it simple
          };
        }
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    // Merge provided attributes with the ones generated by addAttributes
    return ['span', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
  },

  addCommands() {
    return {
      setAiHighlight:
        (attributes) =>
        ({ commands }) => {
          return commands.setMark(this.name, attributes);
        },
      unsetAiHighlight:
        () =>
        ({ commands }) => {
          return commands.unsetMark(this.name);
        },
    };
  },
});

